### ISSUE TITLE
Изучить виды лицензий

### ISSUE THREAD

**Issue by ik6cgsg** [ik6cgsg/3-Days-of-Vanished-Realm#137]

**Comment by OLavrik** [comment]
1.   Freeware - свободно распространяемые (БЕСПЛАТНЫЕ) полнофункциональные программы.
2.   Shareware - условно-бесплатное программное обеспечение -  пользователю бесплатно предоставляется программное обеспечение неполного функционала. (demo)-не весь функционал (trial)-на время весь функционал
3.   Public domain software - бесплатное пользование и автор отказывается от своих прав.
4.   Open Source - программное обеспечение распространяется на бесплатной основе вместе с исходным кодом. Однако автор уже не отказывается от своих прав.
5.   Commercial - платное.

**Comment by mashaverdina** [comment]
Там в Open Source еще куча своих заморочек (лицензий). Что-то более-менее приличное чаще всего под этой категорией.

**Comment by OLavrik** [comment]
# Лицензии OpenSource
### GNU 
##### GLP
Пользователь имеет право распространять ПО под этой лицензией, участвовать в его разработке или изменять различными способами. Но есть такое правило: любые изменения программы, сделанные пользователем и распространенные им, должны иметь исходный код этих изменений.

#### LGPL
Дает больше прав, чем GPL. Главное отличие в том, что она позволяет использовать продукты LGPL в проектах, которые распространяются под другими лицензиями.

### Apache License
Некоторые из доступных прав: права безвозмездны, вечны, не эксклюзивны и глобальны. Если вы распространяете код, вы должны указать имя разработчика.

### BSD
Разработчики должны выполнить несложные условия: указывать в документации, что в продукте используются разработки создателей оригинального программного обеспечения и не использовать имена (или названия) создателей этого ПО в рекламных целях без письменного согласия.

### MIT license
Лицензия схожа с BSD. Но в MIT можно использовать название продукта и имена создателей в рекламных целях. 

### Mozilla Public
Содержит в себе черты BSD и GPL. Исходный код, скопированный или измененный под лицензией MPL, должен быть лицензирован по правилам MPL. Лицензия позволяет объединить его в одной программе с проприетарными (несвободными) файлами.

### Common Development and Distribution License
Эта лицензия позволяет совмещать открытый и закрытый код, защищенный авторскими правами. Файлы можно совмещать с файлами, которые находятся под другими открытыми или проприетарными (несвободными) лицензиями.

### Eclipse Public License
Лицензия наиболее подходит для бизнес-ориентированного свободного ПО и базируется на лицензии CPL. У нее более гибкие правила отказа на авторские права.

**Comment by OLavrik** [comment]
MIT license - лучший выбор
