### ISSUE TITLE
Проверить работоспособность перед демонстрацией

### ISSUE THREAD

**Issue by ik6cgsg** [ik6cgsg/3-Days-of-Vanished-Realm#141]
- iOS разных версий и моделей
- Android разных моделей с разными разрешениями экрана

**Comment by OLavrik** [comment]
жду ревью по звуку и начинаю тестировать 
наверное стоит все слить в одну ветку

**Comment by ik6cgsg** [comment]
Устройство: Samsung Galaxy s8
Состояние: Летает

**Comment by ik6cgsg** [comment]
Устройство: Huawei Honor 8x
Состояние: Небольшие задержки

**Comment by OLavrik** [comment]
кнопка магнитная на всех айфонах не работает
Iphone 7,x

**Comment by ik6cgsg** [comment]
Основные жалобы:
* Затекают плечи держать кардборд
* Совсем не интуитивно и не понятно, что граффити на стене - это "ковер", который надо поджечь
* Сложно уловить что какой курсор значит (мб вместо зеленого курсора картинка ладони?)
* Во второй комнате без подсказок совсем не понятно, что за серое пятно
* Где конец??? // Отсутствие победного текста/анимации/экрана
* Неестественное "нажатие" (не сразу понятно, насколько резко и в какую сторону дергать магнит)

**Comment by Ppasha9** [comment]
Устройства: Samsung Galaxy S10, IPhone 8
Состояние: отличное
Жалобы: тоже недовольны тем, что нет определенного конца

**Comment by pv6** [comment]
Наконец-то руки дотянулись полностью пройти в виаре

- iPhone SE
- Всё летает
- Магнитная кнопка не воркает, ни с большим магнитом, ни с маленьким
- Инвентарь рисуется всё-таки далековато, на нём реально трудно сфокусироваться
- Некоторые глифы мерцают, надо их отодвинуть от стены
- Кружочки на полу в синей комнате мерцают, их тоже надо сдвинуть
- Кнопку в серой комнате реально трудно разглядеть, исправим
- Разводы на очках выглядят плохо; на них можно сфокусироваться и понять, что это просто шар вокруг тебя; мне кажется их стоит убрать и оставить просто зеленую текстуру
- Звук шагов сейчас как звук прыжка
- Комнаты вообще не маленькие в 3Д, хз. Клаустрофобии у меня не возникало
- У поднимающейся стены, соединяющей красную и белую комнаты, не выставлен звук
- У крокодилов надо бы звук в начале чуть обрезать, я думаю. А то они начинают скрипеть только уже к середине анимации
- Решетка в первой комнате надо чтобы поднималась подольше. Не успел повернуться, она уже поднята, не понятно, что произошло

**Comment by pv6** [comment]
Проверил на компе, всё проходится от начала до конца, всё что нужно вроде сохраняется
Проверьте с утра на мобильном телефоне

**Comment by ik6cgsg** [comment]
Прошел всю игру, все круто, только не работает звук у Pickupable почему то((((((((((
