### ISSUE TITLE
Добавить звук открывающейся двери

### ISSUE THREAD

**Issue by pv6** [ik6cgsg/3-Days-of-Vanished-Realm#154]

**Comment by OLavrik** [comment]
Я правильно понимаю,  что стоит добавить 2 звука....когда ключа нет и когда есть и дверь открывается или не запариваться?

**Comment by ik6cgsg** [comment]
Пока достаточно добавить звук именно открывающейся двери, то есть скрежет там, скрипение при поднятии двери, ну а это происходит непосредственно когда есть ключ и игрок вызвал Interact
