### ISSUE TITLE
Добавить проигрывание звука в интерактивный объект

### ISSUE THREAD

**Issue by pv6** [ik6cgsg/3-Days-of-Vanished-Realm#156]
- Разобраться, как воспроизводить звук
- Переименовать IInteractiveObject.Interact на какой-нибудь InteractVirtual(), поменять соответственно все файлы
- Добавить не виртуальный IInteractiveObject.Ineract(), который сначала проигрывает звук, а потом вызывает InteractVirtual(). Должно, вроде как, работать
- Звук каждый переопределяет в каком-нибудь virtual Sound interactSound { get { return null; } }
- Если остался null, то звука нет

**Comment by ik6cgsg** [comment]
На сцене лежит объект-пример Detector
Для добавления звука необходимо:
1) Создать компоненту Audio Source
2) В контроллер своего объекта добавить публичную ссылку soundRef на аудио
3) Кинуть в ссылку созданную в первом пункте компоненту
4) Переопределить Sound{ get{ return soundRef }}
