### ISSUE TITLE
Найти, откуда легально брать звуки

### ISSUE THREAD

**Issue by pv6** [ik6cgsg/3-Days-of-Vanished-Realm#161]

**Comment by ik6cgsg** [comment]
Я так понимаю здесь все можно легально скачивать
>https://www.audiomicro.com/free-sound-effects   

Зарегал нас
>Username: scrumgays 
>Password: 3dvristhebest

**Comment by decentNick** [comment]
Вот еще сайт:
https://wav-library.net
