### ISSUE TITLE
Выбрать стандарт кодирования и добавить информацию о нем в ReadMe.md

### ISSUE THREAD

**Issue by ik6cgsg** [ik6cgsg/3-Days-of-Vanished-Realm#19]

**Comment by mashaverdina** [comment]
Раз это существующий стандарт, просто в разделе Coding Standard просто добавьте ссылку на него

**Comment by mashaverdina** [comment]
Если что-то менялось, то нужно вынести в отдельный файл `CodingStandard.md`, а на него уже дать ссылку в `ReadMe.md`.
Еще нужно добавить примеры, как надо и, может быть, даже как не надо.
см. в качестве примера https://docs.google.com/viewer?a=v&pid=sites&srcid=ZGVmYXVsdGRvbWFpbnx5YXAxMDU3fGd4OjViNTc3MTU2ZTViYWU2OGM
