### ISSUE TITLE
Спроектировать главное меню

### ISSUE THREAD

**Issue by ik6cgsg** [ik6cgsg/3-Days-of-Vanished-Realm#198]

**Comment by pv6** [comment]
![menu.png](https://images.zenhubusercontent.com/5c7d470fa3de12186f507ae7/924e35ad-8227-4dc4-8498-1e77ba72644d)![menu2.png](https://images.zenhubusercontent.com/5c7d470fa3de12186f507ae7/07630d25-e30a-4eb5-ac25-1fa40616edf0)
