### ISSUE TITLE
Общее описание продукта и основной функциональности в ReadMe.md

### ISSUE THREAD

**Issue by ik6cgsg** [ik6cgsg/3-Days-of-Vanished-Realm#20]

**Comment by mashaverdina** [comment]
Не очень понимаю, к чему там надпись SpbPU
Functionality тут не подходит, обычно пишут Features или Basic features. Но у вас игра, так что можно как-то иначе назвать. Game Experience? тоже, наверное, не совсем то. Или просто поставить сразу после описания? Что думаете?

**Comment by OLavrik** [comment]
Хорошо, попытаюсь подобрать слова... только у  меня вопрос тут обычно пишут инструкцию для разработчиков и я не видела когда в реадми пишут для конечного пользователя
Если и добавлять сюда для конечного пользователя то как назвать или под пункт в Get Starting?
