### ISSUE TITLE
Разработать сценарий демо-уровня

### ISSUE THREAD

**Issue by ik6cgsg** [ik6cgsg/3-Days-of-Vanished-Realm#40]

**Comment by pv6** [comment]
![demo level.png](https://images.zenhubusercontent.com/5c7d470fa3de12186f507ae7/55071288-744f-45ad-8583-c13f812b6854)![demo level no notes.png](https://images.zenhubusercontent.com/5c7d470fa3de12186f507ae7/aa195aab-a6a3-40cc-969f-7de0df28fd5f)
