### ISSUE TITLE
Инструкция по установке для разработчиков

### ISSUE THREAD

**Issue by ik6cgsg** [ik6cgsg/3-Days-of-Vanished-Realm#63]

**Comment by mashaverdina** [comment]
Здесь нужна подробная инструкция, что и в каком порядке устанавливать. Со ссылками на то, что нужно скачать: сайт, откуда скачать Unity, еще какие-то sdk. Как собрать, как запустить, отлаживать - для разработчика. Можно, например, оставить getting started, а более подробную в какой-то еще файл и дать ссылку.

**Comment by mashaverdina** [comment]
Open project using your IDEA - так открывать идею или икскод/студию?
Я запуталась в инструкции - сначала вы говорите открыть в студии, а потом - откройте юнити и запустите. Это нужно, запускать оба? В таком порядке?
Зачем мне сначала запускать студию, потом открывать в ней какой-то проект, и только потом клонировать? 
А даже когда я клонирую, какой проект мне открыть? Какой файл - это файл проекта?
В общем, я ничего не поняла из инструкции(

**Comment by mashaverdina** [comment]
Нужно теперь сделать инструкцию связной. Использовать больше полных предложений.


> Development environment under C# + Unity sdk.
> Unity sdk (minimum version: 5.6)

Это одно предложение.

> Development environment under C# (preferred):

Что preferred? С#? Еще тут и далее номера означают последовательность действий, а у вас это все-таки выбор, так что лучше буллиты.

>You need to open projects folder 3-Days-of-Vanished-Realm with Unity .

Здесь и еще в некоторых местах пробелы перед точкой. Предлог with вроде бы неправильный (via? in?). Внезапно появляется "you need", хотя раньше везде было просто "clone". 

> Set compilations preferences:
> 
> for iOS instruction
> or Windows you use automatic settings.

Тут просто посреди предложения вставили цифры, никак не отредактировав. можно сделать так же, как в разделе про икскод и студию.

> Then click on "Build", and you will get project for developer mode .

Тут тоже точка, нужно как-то перестроить, чтобы не было кликни. Что-то типа соберите приложение и в скобках можно указать опцию меню в юнити.

В целом нужно на свежую голову все вычитать.

**Comment by mashaverdina** [comment]
Все те же старые ошибки не исправлены. Много опечаток. В некоторых старых местах - несвязный набор слов. Может быть стоить кому-то посмотреть свежим взглядом.

**Comment by mashaverdina** [comment]
Я бы не использовала слово Instruction, тут больше, наверное, подходит guide (какое-то еще?). Можно, наверное, назвать Installation Guide
