### ISSUE TITLE
Добавить инструкцию по запуску

### ISSUE THREAD

**Issue by ik6cgsg** [ik6cgsg/3-Days-of-Vanished-Realm#64]

**Comment by mashaverdina** [comment]
Здесь на самом деле краткая версия того, что скачать, как загрузить себе на телефон, без подробностей про разработку/отладку. Для людей, которые просто хотя себе релизную версию файлика. Возможно, это как раз то, что останется, в ReadMe от #63.

**Comment by mashaverdina** [comment]
Смотри, вы в маркеты еще не известно когда опубликуетесь (и опубликуетесь ли). Так что стоит добавить в инструкцию, как сейчас это сделать. То есть, например, публиковать где-то apk и сказать, что его нужно скачать и установить. Если на айфон можно только через мак, то так и напишите, что если не мак, то нам очень жаль, подождите, пока не зарелизим. Если мак, то делайте это и это.
